version: '3.8'
services:
  notebook:
    build: .
    ports:
      - '1515:8888'
    volumes:
      - ./notebook:/home/jovyan/work
      - /mnt:/mnt
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
